name: Mirror to GitLab (main only)

on:
  push:
    branches:
      - "main"   

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout completo (evita shallow update error)
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2) Configurar SSH para GitLab
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITLAB_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts

      # 3) Push a GitLab SOLO en main
      - name: Push to GitLab
        run: |
          git remote add gitlab git@gitlab.com:milagrosgoiris42/pedidos_lumen.git
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # Fuerza actualizaci√≥n del branch main en GitLab
          git push --force gitlab main


      - name: Push to GitLab
        run: |
          git remote add gitlab "${{ secrets.GITLAB_REPO_URL }}"
          git push gitlab main --force
